=== monicacaseys/publica/fullxml/CANCIONXML.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="ballet">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo"/>
                <xs:element ref="compositor"/>
                <xs:element ref="autor"/>
                <xs:element ref="genero"/>
                <xs:element ref="historia"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="compositor" type="xs:string"/>
    <xs:element name="autor" type="xs:string"/>
    <xs:element name="genero" type="xs:string"/>
    <xs:element name="historia">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="acto"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="acto">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="escena"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="escena" type="xs:string"/>
</xs:schema>

=== monicacaseys/publica/fullxml/CANCIONXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="CANCIONXSL.xsl"?> 
<ballet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CANCIONXML.xsd">
	<titulo>The Best of Both Worlds</titulo>
	<autor>Hannah Montana</autor>
	<genero>Pop </genero>
<historia>
	    <acto>
			<escena>You get the limo out front (ooh-aah-ooh)</escena>	
		</acto>
		<acto>
			<escena>Don't ever say it's over if I'm breathin'</escena>			
		</acto>
		<acto>
			<escena>Been that ni* since I came out my mama (woo)</escena>		
		</acto>
</historia>
</ballet>
